### ISSUE TITLE
thank you so much!

### ISSUE THREAD

**Issue by travnewmatic** [yakumo-saki/k8s-mastodon-deployment#1]
while i did not use your files exactly, these were an EXCELLENT REFERENCE.  just got my mastodon server up and running on my cluster with the help of your manifests.  add me if ya wanna!~  @travis@toot.travnewmatic.com

**Comment by yakumo-saki** [comment]
Thank you for using this as reference. 
I'm very very happy to hear that. Thank you, really thank you for your comment !
